### ISSUE TITLE
升级到0.2.3后出问题了

### ISSUE THREAD

**Issue by Anonymous-W** [biezhi/anima#32]
Caused by: java.lang.IllegalArgumentException: Unable to find non-private method: getRush with 0 params.
	at com.blade.reflectasm.MethodAccess.getIndex(MethodAccess.java:74)
	at com.blade.reflectasm.MethodAccess.invokeWithCache(MethodAccess.java:47)
	at io.github.biezhi.anima.utils.AnimaUtils.invokeMethod(AnimaUtils.java:147)
	at io.github.biezhi.anima.utils.AnimaUtils.toColumnValues(AnimaUtils.java:101)

调用save时出现的，rush是个boolean

**Comment by xiwenAndlejian** [comment]
你可能使用了lombok，或者自动生成的get/set方法，boolean的get方法会生成为isXXXX，eg：
```java
boolean success;
...
public boolean isSuccess(){
  return success;
}
...
```
修改方法：
1. 使用包装类`Boolean`
2. 手动写一个`getXXX`的方法

**Comment by Anonymous-W** [comment]
@xiwenAndlejian 多谢指教，确实是这个问题，疏忽了，不过比较好奇为啥升级后才出现这个问题

**Comment by biezhi** [comment]
yes，目前在 anima 中都是使用包装类的，因为一个很重要的原因：

**我们在做新增、更新操作的时候基础类型会有默认值**

所以目前建议都使用包装类型，如果对该原因有其他想法可以继续探讨。
