### ISSUE TITLE
AnimaCache中的METHOD_ACCESS_MAP等等在并发状态下会出错

### ISSUE THREAD

**Issue by shenzhou-6** [biezhi/anima#42]
```java
Exception in thread "main" java.util.concurrent.CompletionException: java.util.ConcurrentModificationException
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:840)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.util.ConcurrentModificationException
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
	at io.github.biezhi.anima.utils.AnimaUtils.invokeMethod(AnimaUtils.java:129)
	at io.github.biezhi.anima.utils.AnimaUtils.toColumnValues(AnimaUtils.java:99)
	at io.github.biezhi.anima.core.AnimaQuery.save(AnimaQuery.java:1203)
	at io.github.biezhi.anima.Model.save(Model.java:28)
```

**Comment by biezhi** [comment]
你是否使用了 JDK 8 以上的版本，目前我还未在高版本中测试过，如果 JDK 8 可以重现，发一下这个代码片段 :_)

**Comment by shenzhou-6** [comment]
`public class Demo {
    public static void main(String[] args) {
        Anima.open("jdbc:mysql://127.0.0.1:3306/test", "root", "123456");
        List<Demos> demos = new ArrayList<>();
        for (int i = 0; i < 10; i++) {
            Demos demo = new Demos(i,String.valueOf(i));
            demos.add(demo);
        }

        CompletableFuture.allOf(demos.stream()
                .map(demos1 -> CompletableFuture.supplyAsync(() -> demos1.save()))
                .toArray(CompletableFuture<?>[]::new))
                .join();


    }
}


class Demos extends Model {
    private Integer id;

    private String content;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Demos(Integer id, String content) {
        this.id = id;
        this.content = content;
    }
}`

**Comment by shenzhou-6** [comment]
我测试了下，其实是在jdk11下才会报这个错，在jdk8的时候是没有这个错的。

在jdk11中 HashMap的 computeIfAbsent 方法多了一个

![image](https://user-images.githubusercontent.com/40198505/49414959-201ee300-f7b0-11e8-80f9-61c755f026e4.png)

**Comment by biezhi** [comment]
已经使用 `ConcurrentHashMap` 了，在 `0.2.5` 版本。
