### ISSUE TITLE
Using Anima.deleteBatch get an exception

### ISSUE THREAD

**Issue by nguereza-tony** [biezhi/anima#64]
Hello when using the method **Anima.deleteBatch** I got an exception see below for the details.

**Example code:**
```java
List<Integer> ids = Arrays.asList(1,2,3);
Anima.deleteBatch(User.class, ids);
```
**--User.java**
```java
import java.util.Date;

import io.github.biezhi.anima.Model;
import lombok.Data;
import lombok.EqualsAndHashCode;

@Data
@EqualsAndHashCode(callSuper = true)
public class User extends Model{

	private Integer id;
	private String username;
	private String lastname;
	private String firstname;
	private String email;
	private String password;
	private Boolean status;
	private Date createdAt = new Date();
	private Date updatedAt = new Date();
	
	public User() {}
}
```
**Anima version:** 0.2.6

--**Exception details**
2020-08-31 13:09:01.725 ERROR [worker@thread-1] io.github.biezhi.anima.Anima - Batch save model error, message: {}
org.sql2o.Sql2oException: Could not acquire a connection from DataSource - wait millis 6000, active 5, maxActive 5, creating 0
	at org.sql2o.Connection.createConnection(Connection.java:300) ~[anima-0.2.6.jar:na]
	at org.sql2o.Connection.<init>(Connection.java:69) ~[anima-0.2.6.jar:na]
	at org.sql2o.Connection.<init>(Connection.java:62) ~[anima-0.2.6.jar:na]
	at org.sql2o.Sql2o.open(Sql2o.java:170) ~[anima-0.2.6.jar:na]
	at io.github.biezhi.anima.core.AnimaQuery.getConn(AnimaQuery.java:1496) ~[anima-0.2.6.jar:na]
	at io.github.biezhi.anima.core.AnimaQuery.execute(AnimaQuery.java:1199) ~[anima-0.2.6.jar:na]
	at io.github.biezhi.anima.core.AnimaQuery.execute(AnimaQuery.java:1219) ~[anima-0.2.6.jar:na]
	at io.github.biezhi.anima.core.AnimaQuery.delete(AnimaQuery.java:1256) ~[anima-0.2.6.jar:na]
	at io.github.biezhi.anima.core.AnimaQuery.deleteById(AnimaQuery.java:1268) ~[anima-0.2.6.jar:na]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source) ~[na:1.8.0_181]
	at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source) ~[na:1.8.0_181]
	at io.github.biezhi.anima.Anima.lambda$deleteBatch$4(Anima.java:420) [anima-0.2.6.jar:na]
	at io.github.biezhi.anima.Anima.atomic(Anima.java:225) [anima-0.2.6.jar:na]
	at io.github.biezhi.anima.Anima.deleteBatch(Anima.java:419) [anima-0.2.6.jar:na]
	at io.github.biezhi.anima.Anima.deleteBatch(Anima.java:433) [anima-0.2.6.jar:na]
	at cf.iacademy.budgetmgr.services.PermissionService.deleteMany(PermissionService.java:123) ~[classes/:na]
	at cf.iacademy.budgetmgr.controllers.PermissionController.delete(PermissionController.java:184) ~[classes/:na]
	at cf.iacademy.budgetmgr.controllers.PermissionControllerMethodAccess.invoke(Unknown Source) ~[blade-asm-0.0.4.jar:na]
	at com.blade.reflectasm.MethodAccess.invoke(MethodAccess.java:43) ~[blade-asm-0.0.4.jar:na]
	at com.blade.server.netty.RouteMethodHandler.routeHandle(RouteMethodHandler.java:256) ~[blade-mvc-2.0.15.RELEASE.jar:na]
	at com.blade.server.netty.RouteMethodHandler.handle(RouteMethodHandler.java:87) ~[blade-mvc-2.0.15.RELEASE.jar:na]
	at com.blade.server.netty.HttpServerHandler.executeLogic(HttpServerHandler.java:159) ~[blade-mvc-2.0.15.RELEASE.jar:na]
	at java.util.concurrent.CompletableFuture.uniApply(Unknown Source) ~[na:1.8.0_181]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source) ~[na:1.8.0_181]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[na:1.8.0_181]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[netty-common-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[netty-common-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497) ~[netty-transport-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.48.Final.jar:4.1.48.Final]
	at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_181]
Caused by: com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 6000, active 5, maxActive 5, creating 0
	at com.alibaba.druid.pool.DruidDataSource.getConnectionInternal(DruidDataSource.java:1734) ~[druid-1.1.23.jar:1.1.23]
	at com.alibaba.druid.pool.DruidDataSource.getConnectionDirect(DruidDataSource.java:1404) ~[druid-1.1.23.jar:1.1.23]
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1384) ~[druid-1.1.23.jar:1.1.23]
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1374) ~[druid-1.1.23.jar:1.1.23]
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:98) ~[druid-1.1.23.jar:1.1.23]
	at org.sql2o.connectionsources.DataSourceConnectionSource.getConnection(DataSourceConnectionSource.java:26) ~[anima-0.2.6.jar:na]
	at org.sql2o.Connection.createConnection(Connection.java:297) ~[anima-0.2.6.jar:na]
	... 30 common frames omitted

**Comment by nguereza-tony** [comment]
The problem is not anima but the configuration of data source.
Close the issue
